services:
  mongodb:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - analytics_mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 2s
      timeout: 5s
      retries: 15

volumes:
  analytics_mongodb_data:
