import React, { Suspense,lazy,useCallback,useEffect,useMemo,useState } from 'react'
import { getDashboard,getModelCard,errorMessage } from '../services/api'
import type { DashboardData,KpiKey,ModelCard } from '../types'
import { ThemeToggle } from '../components/ThemeToggle'
const LazyRevenue=lazy(()=>import('../components/PortfolioCharts').then(module=>({default:module.RevenueChart})))
const LazyCountry=lazy(()=>import('../components/PortfolioCharts').then(module=>({default:module.CountryChart})))

const kpiNames:Record<KpiKey,string>={revenue:'Sales revenue',orders:'Orders',customers:'Identified customers',averageOrderValue:'Average order value'}
const formatValue=(key:KpiKey,value:number)=>key==='revenue'||key==='averageOrderValue'?new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:key==='revenue'?0:2}).format(value):new Intl.NumberFormat('en-GB',{maximumFractionDigits:0}).format(value)
const shortMoney=(v:number)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',notation:'compact',maximumFractionDigits:1}).format(v)

export default function Dashboard(){
 const [data,setData]=useState<DashboardData|null>(null),[model,setModel]=useState<ModelCard|null>(null),[modelUnavailable,setModelUnavailable]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const [filters,setFilters]=useState({from:'',to:'',country:'All'})
 const load=useCallback(async(next?:typeof filters)=>{setLoading(true);setError('');setModelUnavailable(false);try{const dashboard=await getDashboard(next?.from?next:undefined);setData(dashboard);setFilters({from:dashboard.meta.from,to:dashboard.meta.to,country:dashboard.meta.country});try{setModel(await getModelCard())}catch{setModel(null);setModelUnavailable(true)}}catch(e){setError(errorMessage(e))}finally{setLoading(false)}},[])
 useEffect(()=>{void load()},[load])
 const mixTotal=(data?.customerMix.new||0)+(data?.customerMix.returning||0)
 const generatedLabel=useMemo(()=>data?new Date(data.meta.generatedAt).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):'',[data])
 return <div className="app-shell">
  <a className="skip-link" href="#main">Skip to dashboard</a>
  <header className="site-header"><div className="brand"><span className="brand-mark">RA</span><span>Retail Analytics</span></div><div className="header-actions"><span className="case-label">Historical case study · 2010–2011</span><ThemeToggle/></div></header>
  <main id="main" className="page" aria-busy={loading}>
   <section className="hero"><div><p className="eyebrow">UCI ONLINE RETAIL · EXPLAINABLE ANALYTICS</p><h1>What shaped the year in retail?</h1><p className="lede">A transparent view of revenue, customers and demand—built from {data?`${data.meta.cleanTransactions.toLocaleString()} cleaned transactions`:'real transactions'}, with every forecast measured against a baseline.</p></div><div className="hero-note"><span>Dataset coverage</span><strong>{data?`${data.meta.startDate} — ${data.meta.endDate}`:'2010-12-01 — 2011-12-09'}</strong><a href="https://archive.ics.uci.edu/dataset/352/online-retail" target="_blank" rel="noreferrer">View source ↗</a></div></section>
   <form className="filters" onSubmit={e=>{e.preventDefault();void load(filters)}}><label>From<input type="date" value={filters.from} min={data?.meta.startDate} max={filters.to||data?.meta.endDate} onChange={e=>setFilters({...filters,from:e.target.value})}/></label><label>To<input type="date" value={filters.to} min={filters.from||data?.meta.startDate} max={data?.meta.endDate} onChange={e=>setFilters({...filters,to:e.target.value})}/></label><label>Market<select value={filters.country} disabled={loading} onChange={e=>{const next={...filters,country:e.target.value};setFilters(next);void load(next)}}><option>All</option>{data?.filters.countries.map(x=><option key={x}>{x}</option>)}</select></label><button className="button primary" type="submit" disabled={loading}>Apply view</button></form>
   {error&&<section className="state error" role="alert"><strong>We couldn’t load the analysis.</strong><p>{error}</p><button className="button primary" onClick={()=>void load()}>Try again</button></section>}
   {loading&&!data&&<section className="state" role="status"><span className="loader"/>Preparing the retail analysis…</section>}
   {data&&<div id="dashboard-content" className={loading?'dashboard muted':'dashboard'}>
    <section className="kpi-grid" aria-label="Key performance indicators">{data.kpis.map(kpi=><article className="kpi" key={kpi.key}><p>{kpiNames[kpi.key]}</p><strong>{formatValue(kpi.key,kpi.value)}</strong><span className={kpi.comparisonPercent==null?'neutral':kpi.comparisonPercent>=0?'positive':'negative'}>{kpi.comparisonPercent==null?'No prior comparison':`${kpi.comparisonPercent>=0?'↑':'↓'} ${Math.abs(kpi.comparisonPercent).toFixed(1)}% vs prior period`}</span></article>)}</section>
    <section className="panel wide"><div className="panel-heading"><div><p className="eyebrow">REVENUE SIGNAL</p><h2>Actual revenue and forward view</h2></div>{data.anomalies.length>0&&<div className="legend-note"><i className="dot anomaly"/> {data.anomalies.length} unusual days in view</div>}</div><Suspense fallback={<div className="chart-loading">Loading visualization…</div>}><LazyRevenue data={data}/></Suspense><p className="chart-summary">Revenue series from {data.revenueSeries.length} observed days. {data.forecasts.length?`The dotted extension shows a ${data.forecasts.length}-day model forecast with a 90% held-out residual interval.`:'Forecasts are shown only for the complete dataset because filtered views have not been independently backtested.'}</p></section>
    <div className="two-column"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">MARKET MIX</p><h2>Revenue by country</h2></div></div><Suspense fallback={<div className="chart-loading">Loading visualization…</div>}><LazyCountry rows={data.countries}/></Suspense></section>
    <section className="panel"><div className="panel-heading"><div><p className="eyebrow">CUSTOMER MIX</p><h2>New and returning order activity</h2></div></div><div className="mix"><div className="donut" style={{'--new':`${mixTotal?data.customerMix.new/mixTotal*100:0}%`} as React.CSSProperties}><span>{mixTotal?Math.round(data.customerMix.returning/mixTotal*100):0}%<small>returning</small></span></div><dl><div><dt><i className="dot new"/>First-purchase orders</dt><dd>{data.customerMix.new.toLocaleString()}</dd></div><div><dt><i className="dot returning"/>Repeat-purchase orders</dt><dd>{data.customerMix.returning.toLocaleString()}</dd></div></dl></div><p className="footnote">Order activity includes identified customers only. The customer KPI de-duplicates those IDs across the selected period.</p></section></div>
    <div className="two-column"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">PRODUCT PERFORMANCE</p><h2>Products creating value</h2></div></div><div className="table-wrap"><table><thead><tr><th>Product</th><th>Units</th><th>Revenue</th></tr></thead><tbody>{data.products.map(row=><tr key={row.stockCode}><td><strong>{row.name}</strong><small>{row.stockCode}</small></td><td>{Math.round(row.units).toLocaleString()}</td><td>{shortMoney(row.revenue)}</td></tr>)}</tbody></table></div></section>
    <section className="panel insights"><div className="panel-heading"><div><p className="eyebrow">MODEL-BACKED READOUT</p><h2>What deserves attention</h2></div></div>{data.insights.length?data.insights.map(item=><article key={item.id} className="insight"><span className={`insight-kind ${item.kind}`}>{item.kind}</span><h3>{item.title}</h3><p>{item.summary}</p><strong>{item.evidence}</strong><small>{item.period} · {item.modelVersion}</small></article>):<div className="empty"><strong>No generalized claims for this slice.</strong><p>Insights are withheld for filtered views until the model has been evaluated on that segment.</p></div>}</section></div>
    {modelUnavailable&&<section className="model-unavailable" role="status"><strong>Model diagnostics are temporarily unavailable.</strong><span>The transactional analysis remains available; no substitute results are shown.</span></section>}
    {model&&<section className="model-card"><div><p className="eyebrow">MODEL CARD · {model.version}</p><h2>Forecast quality, in plain view</h2><p>{model.algorithm}, evaluated with rolling time-series splits. Compared with: {model.baseline.toLowerCase()}.</p></div><dl><div><dt>WAPE</dt><dd>{model.wape}%</dd></div><div><dt>Baseline WAPE</dt><dd>{model.baselineWape}%</dd></div><div><dt>MAE</dt><dd>{shortMoney(model.mae)}</dd></div><div><dt>Horizon</dt><dd>{model.forecastHorizonDays} days</dd></div></dl><details><summary>Limitations and methodology</summary><ul>{model.limitations.map(x=><li key={x}>{x}</li>)}</ul></details></section>}
    <footer className="data-footer"><p><strong>{data.meta.name}</strong> · {data.meta.license} · DOI {data.meta.doi}</p><p>Artifact dated {generatedLabel}. Historical data; not live commerce activity.</p></footer>
   </div>}
  </main>
 </div>
}
